services:
  postgres:
    image: postgres:16
    container_name: hidoc_postgres
    restart: always
    environment:
      POSTGRES_USER: hidoc_user
      POSTGRES_PASSWORD: hidoc_pass
      POSTGRES_DB: hidoc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: hidoc_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
